# For all pushes to the main branch run the tests and push the image to the
# GitHub registry under an edge tag so we can use it for the nightly
# integration tests
on:
  push:
    branches: main

jobs:
  validation_job:
    runs-on: ubuntu-latest
    name: Checkout
    steps:
      - name: Validation Step
        id: all
        uses: actions/checkout@main
        with:
          validation-type: 'All'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.all.outputs.time }}"
