on: [push]

jobs:
  validation_job:
    runs-on: ubuntu-latest
    name: SCI-G Validation
    steps:
      - name: Validation Step
        id: all
        uses: actions/gemc/sci-g@v1
        with:
          validation-type: 'All'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.all.outputs.time }}"
