# For all pushes to the main branch run the tests and push the image to the
# GitHub registry under an edge tag so we can use it for the nightly
# integration tests
name: geometry

on:
  push:
  pull_request:

jobs:
  validation_job:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:3.0
    name: Sci-g Geometry Validation for ${{ matrix.dir }}
    strategy:
      matrix:
        include:
          - dir: examples/1_Simple_detector/ex1_1_simple_det
            script: example.py
            gcard: example.jcard
          - dir: examples/1_Simple_detector/ex1_2_dosimeter
            script: example.py
            gcard: example.jcard
          - dir: projects/clas12/targets
            script: targets.py
            gcard: target.jcard
    steps:
      # GitHub Actions do not automatically checkout your projects. If you need the code
      # you need to check it out.
      - name: Checkout
        uses: actions/checkout@main
      - name: Add current directory to PYTHONPATH
        run:
          echo "PYTHONPATH=$PWD:$PYTHONPATH" >> "$GITHUB_ENV"
      - name: Run geometry and gemc
        working-directory: ${{ matrix.dir }}
        run: |
          source /etc/profile.d/jlab.sh
          cd ${{ matrix.dir }}
          echo Building Geometry for ${{ matrix.dir }}
          ./${{ matrix.script }}
          echo Running gemc for ${{ matrix.gcard }}
          gemc ${{ matrix.gcard }}
      - name: Check overlaps
        working-directory: ${{ matrix.dir }}
        run: |
          overlaps=`grep G4Exception-START MasterGeant4.log | wc | awk '{print $1}'`
          if (( "$overlaps" == "0" ))
          then
            echo "$overlaps" overlaps detected
          else
            echo "$overlaps" overlaps detected for $example, exiting
            exit 1
          fi
